"""initial schema

Revision ID: e72a1b5d07d7
Revises:
Created: 2026-08-13 02:14:11.872808
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e72a1b5d07d7"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "answers",
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_table(
        "questions",
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("content"),
    )
    op.create_table(
        "answer_questions",
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("answer_uid", sa.UUID(), nullable=False),
        sa.Column("question_uid", sa.UUID(), nullable=False),
        sa.Column("point_uid", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["answer_uid"], ["answers.uid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["question_uid"], ["questions.uid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("answer_uid", "question_uid", name="uq_answer_questions_pair"),
        sa.UniqueConstraint("point_uid"),
    )
    op.create_index(
        op.f("ix_answer_questions_answer_uid"), "answer_questions", ["answer_uid"], unique=False
    )
    op.create_index(
        "ix_answer_questions_pending",
        "answer_questions",
        ["answer_uid"],
        unique=False,
        postgresql_where=sa.text("point_uid IS NULL"),
    )
    op.create_index(
        op.f("ix_answer_questions_question_uid"), "answer_questions", ["question_uid"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_answer_questions_question_uid"), table_name="answer_questions")
    op.drop_index(
        "ix_answer_questions_pending",
        table_name="answer_questions",
        postgresql_where=sa.text("point_uid IS NULL"),
    )
    op.drop_index(op.f("ix_answer_questions_answer_uid"), table_name="answer_questions")
    op.drop_table("answer_questions")
    op.drop_table("questions")
    op.drop_table("answers")
    # ### end Alembic commands ###
