"""chat session and message

Revision ID: 01c78990cb53
Revises: e72a1b5d07d7
Created: 2026-08-14 00:39:01.234719
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "01c78990cb53"
down_revision: str | None = "e72a1b5d07d7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session",
        sa.Column("session_uid", sa.UUID(), nullable=False),
        sa.Column("user_uid", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("session_uid"),
    )
    op.create_index(op.f("ix_session_user_uid"), "session", ["user_uid"], unique=False)
    op.create_table(
        "message",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_uid", sa.UUID(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["session_uid"], ["session.session_uid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_message_session_uid"), "message", ["session_uid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_message_session_uid"), table_name="message")
    op.drop_table("message")
    op.drop_index(op.f("ix_session_user_uid"), table_name="session")
    op.drop_table("session")
    # ### end Alembic commands ###
